### ISSUE TITLE
How to put the colors

### ISSUE THREAD

**Issue by ceskvfx** [dovanbel/tk-nuke-autolabel#1]
Hi, firt of all thanks for your hard work. I have a stupid question. I tried to set up wih these, but the colors are giving me error? What is the correct way to imput the values of the colors? Always give error. 
Many thanks

other3d_tile_color:
        type: list
        values:
            type: int
            **default_value : '255, 255, 255'**
        description:    "Specify a list of 3 values in the range 0-255 that represent the RGB values to be
                         set for the read node tile_color of non-beauty passes"

**Comment by dovanbel** [comment]
I see, the values of the color should be something like:

[255, 255, 255]

instead of '255, 255, 255'.

In other words, it's a list of rgb values, not a string. I should probably add that to the info.yml as default values

**Comment by dovanbel** [comment]
I made a new version (tag v0.0.4), adding default values in the info.yml so it should be easier to see what's expected

**Comment by ceskvfx** [comment]
Brilliant I will try if  I can find some free time. Thanks!!!!
